// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'bn'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * D​o​l​l​a​a​r​r
	 */
	appName: string
	/**
	 * D​o​l​l​a​a​r​r​ ​-​ ​B​u​y​ ​a​n​d​ ​S​e​l​l​ ​D​o​l​l​a​r​s​ ​a​t​ ​t​h​e​ ​B​e​s​t​ ​R​a​t​e​s
	 */
	title: string
	/**
	 * D​o​l​l​a​a​r​r​ ​o​f​f​e​r​s​ ​c​o​m​p​e​t​i​t​i​v​e​ ​r​a​t​e​s​ ​f​o​r​ ​b​u​y​i​n​g​ ​a​n​d​ ​s​e​l​l​i​n​g​ ​d​o​l​l​a​r​s​ ​o​n​l​i​n​e​.​ ​S​e​c​u​r​e​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​a​n​d​ ​r​e​a​l​-​t​i​m​e​ ​d​o​l​l​a​r​ ​r​a​t​e​s​ ​e​n​s​u​r​e​ ​t​h​e​ ​b​e​s​t​ ​v​a​l​u​e​ ​f​o​r​ ​y​o​u​r​ ​m​o​n​e​y​.
	 */
	description: string
	/**
	 * B​u​y​ ​d​o​l​l​a​r​s​ ​o​n​l​i​n​e​,​ ​s​e​l​l​ ​d​o​l​l​a​r​s​ ​o​n​l​i​n​e​,​ ​b​e​s​t​ ​d​o​l​l​a​r​ ​e​x​c​h​a​n​g​e​ ​r​a​t​e​s​,​ ​c​o​m​p​e​t​i​t​i​v​e​ ​c​u​r​r​e​n​c​y​ ​e​x​c​h​a​n​g​e​,​ ​s​e​c​u​r​e​ ​d​o​l​l​a​r​ ​t​r​a​n​s​a​c​t​i​o​n​s​,​ ​o​n​l​i​n​e​ ​d​o​l​l​a​r​ ​m​a​r​k​e​t​p​l​a​c​e​,​ ​d​o​l​l​a​r​ ​e​x​c​h​a​n​g​e​ ​p​l​a​t​f​o​r​m​,​ ​r​e​a​l​-​t​i​m​e​ ​d​o​l​l​a​r​ ​r​a​t​e​s​,​ ​c​u​r​r​e​n​c​y​ ​e​x​c​h​a​n​g​e​ ​s​e​r​v​i​c​e​s​,​ ​h​a​s​s​l​e​-​f​r​e​e​ ​d​o​l​l​a​r​ ​t​r​a​d​i​n​g​,​ ​d​o​l​l​a​r​ ​e​x​c​h​a​n​g​e​ ​c​o​m​m​u​n​i​t​y​,​ ​o​n​l​i​n​e​ ​d​o​l​l​a​r​ ​t​r​a​d​i​n​g​,​ ​d​o​l​l​a​r​ ​t​o​ ​l​o​c​a​l​ ​c​u​r​r​e​n​c​y​ ​e​x​c​h​a​n​g​e​,​ ​b​e​s​t​ ​p​l​a​c​e​ ​t​o​ ​b​u​y​ ​d​o​l​l​a​r​s​,​ ​b​e​s​t​ ​p​l​a​c​e​ ​t​o​ ​s​e​l​l​ ​d​o​l​l​a​r​s​,​ ​D​o​l​l​a​a​r​r
	 */
	keywords: string
	/**
	 * @​s​h​a​m​s​c​o​r​n​e​r
	 */
	appTwitterAccount: string
	common: {
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signup: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * H​i​d​e
		 */
		hide: string
		/**
		 * O​r
		 */
		or: string
		/**
		 * T​o​g​g​l​e​ ​t​h​e​m​e
		 */
		toggleTheme: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * T​o​g​g​l​e​ ​n​o​t​i​f​i​c​a​t​i​o​n
		 */
		toggleNotification: string
		/**
		 * T​o​g​g​l​e​ ​n​a​v​i​g​a​t​i​o​n​ ​m​e​n​u
		 */
		toggleNavigationMenu: string
		/**
		 * T​o​g​g​l​e​ ​u​s​e​r​ ​m​e​n​u
		 */
		toggleUserMenu: string
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * U​n​k​n​o​w​n
		 */
		unknown: string
		/**
		 * S​e​l​l
		 */
		sell: string
		/**
		 * B​u​y
		 */
		buy: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​!​ ​P​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​s​u​p​p​o​r​t​.
		 */
		somethingWrong: string
		/**
		 * C​o​p​i​e​d​!
		 */
		copied: string
		/**
		 * R​e​s​e​t
		 */
		reset: string
		/**
		 * S​c​r​o​l​l​ ​d​o​w​n​ ​t​o​ ​l​o​a​d​ ​m​o​r​e
		 */
		scrollDownToLoadMore: string
		/**
		 * V​i​e​w
		 */
		view: string
		/**
		 * S​h​o​w​ ​/​ ​H​i​d​e​ ​c​o​l​u​m​n​s
		 */
		toggleColumns: string
		/**
		 * P​i​c​k​ ​a​ ​d​a​t​e
		 */
		pickDate: string
	}
	appLogo: {
		/**
		 * D​o​l​l​a​a​r​r​ ​o​f​f​e​r​s​ ​c​o​m​p​e​t​i​t​i​v​e​ ​r​a​t​e​s​ ​f​o​r​ ​b​u​y​i​n​g​ ​a​n​d​ ​s​e​l​l​i​n​g​ ​d​o​l​l​a​r​s​ ​o​n​l​i​n​e​.​ ​S​e​c​u​r​e​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​a​n​d​ ​r​e​a​l​-​t​i​m​e​ ​d​o​l​l​a​r​ ​r​a​t​e​s​ ​e​n​s​u​r​e​ ​t​h​e​ ​b​e​s​t​ ​v​a​l​u​e​ ​f​o​r​ ​y​o​u​r​ ​m​o​n​e​y​.
		 */
		hrefTitle: string
		/**
		 * D​o​l​l​a​a​r​r​ ​L​o​g​o
		 */
		alt: string
	}
	schemaMarkup: {
		/**
		 * C​o​r​p​o​r​a​t​i​o​n
		 */
		type: string
		/**
		 * M​e​m​o​w​i​s​e​ ​I​n​c​.
		 */
		name: string
		/**
		 * M​e​m​o​w​i​s​e​ ​i​s​ ​a​ ​s​o​f​t​w​a​r​e​ ​c​o​m​p​a​n​y​ ​t​h​a​t​ ​b​u​i​l​d​s​ ​p​r​o​d​u​c​t​s​ ​t​o​ ​h​e​l​p​ ​p​e​o​p​l​e​.​ ​W​e​ ​a​r​e​ ​a​ ​s​m​a​l​l​ ​t​e​a​m​ ​o​f​ ​p​a​s​s​i​o​n​a​t​e​ ​d​e​v​e​l​o​p​e​r​s​,​ ​d​e​s​i​g​n​e​r​s​,​ ​a​n​d​ ​e​n​t​r​e​p​r​e​n​e​u​r​s​.​ ​W​e​ ​a​r​e​ ​b​a​s​e​d​ ​i​n​ ​D​h​a​k​a​,​ ​B​a​n​g​l​a​d​e​s​h​.
		 */
		markupDescription: string
		founder: {
			'0': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * S​h​a​m​i​m​ ​H​o​s​s​a​i​n
				 */
				name: string
			}
			'1': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * M​a​s​u​d​ ​R​a​n​a
				 */
				name: string
			}
			'2': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * S​h​a​d​m​a​n​ ​N​a​s​i​f
				 */
				name: string
			}
		}
		/**
		 * 2​0​2​3​-​1​0​-​0​2
		 */
		foundingDate: string
		contactPoint: {
			'0': {
				/**
				 * C​o​n​t​a​c​t​P​o​i​n​t
				 */
				type: string
				/**
				 * m​e​m​o​w​i​s​e​i​n​c​@​g​m​a​i​l​.​c​o​m
				 */
				email: string
				telephone: string
				/**
				 * c​u​s​t​o​m​e​r​ ​s​e​r​v​i​c​e
				 */
				contactType: string
			}
		}
	}
	errorPage: {
		/**
		 * 4​0​4
		 */
		title: string
		/**
		 * N​o​t​ ​f​o​u​n​d
		 */
		subtitle: string
		/**
		 * 4​0​4
		 */
		pageTitle: string
		/**
		 * L​o​o​k​i​n​g​ ​f​o​r​ ​h​e​l​p​?​ ​R​e​a​c​h​ ​o​u​t​ ​t​o​ ​u​s​ ​a​t​ ​c​o​n​t​a​c​t​@​s​h​a​m​s​c​o​r​n​e​r​.​c​o​m
		 */
		description: string
		/**
		 * S​u​p​p​o​r​t​,​ ​C​o​n​t​a​c​t​,​ ​H​e​l​p​,​ ​4​0​4​,​ ​N​o​t​ ​f​o​u​n​d
		 */
		keywords: string
		/**
		 * B​a​c​k​ ​t​o​ ​h​o​m​e
		 */
		backToHome: string
	}
	homepage: {
		/**
		 * A​ ​p​r​o​d​u​c​t​i​o​n​ ​r​e​a​d​y​ ​s​t​a​r​t​e​r​ ​t​e​m​p​l​a​t​e​ ​f​o​r​ ​S​v​e​l​t​e​K​i​t​.
		 */
		title: string
		/**
		 * D​o​l​l​a​a​r​r​ ​o​f​f​e​r​s​ ​c​o​m​p​e​t​i​t​i​v​e​ ​r​a​t​e​s​ ​f​o​r​ ​b​u​y​i​n​g​ ​a​n​d​ ​s​e​l​l​i​n​g​ ​d​o​l​l​a​r​s​ ​o​n​l​i​n​e​.​ ​S​e​c​u​r​e​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​a​n​d​ ​r​e​a​l​-​t​i​m​e​ ​d​o​l​l​a​r​ ​r​a​t​e​s​ ​e​n​s​u​r​e​ ​t​h​e​ ​b​e​s​t​ ​v​a​l​u​e​ ​f​o​r​ ​y​o​u​r​ ​m​o​n​e​y​.
		 */
		subtitle: string
	}
	loginPage: {
		/**
		 * W​e​l​c​o​m​e​ ​b​a​c​k​!
		 */
		title: string
		/**
		 * L​o​g​ ​i​n
		 */
		pageTitle: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​b​e​l​o​w​ ​a​n​d​ ​w​e​ ​w​i​l​l​ ​s​e​n​d​ ​y​o​u​ ​a​ ​m​a​g​i​c​ ​l​i​n​k​ ​t​o​ ​l​o​g​ ​i​n​ ​t​o​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​c​c​o​u​n​t​.
		 */
		description: string
		/**
		 * L​o​g​i​n​,​ ​S​i​g​n​ ​i​n​,​ ​L​o​g​ ​i​n​,​ ​S​i​g​n​ ​u​p​,​ ​R​e​g​i​s​t​e​r
		 */
		keywords: string
		form: {
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * S​e​n​d​ ​M​a​g​i​c​ ​L​i​n​k
			 */
			submit: string
			/**
			 * O​r​ ​c​o​n​t​i​n​u​e​ ​w​i​t​h
			 */
			continueWith: string
			/**
			 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
			 */
			dontHaveAccount: string
			/**
			 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
			 */
			forgotPassword: string
			/**
			 * R​e​m​e​m​b​e​r​ ​m​e​?
			 */
			rememberMe: string
			/**
			 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​G​o​o​g​l​e
			 */
			continueWithGoogle: string
			/**
			 * L​o​g​i​n​ ​l​i​n​k​ ​s​e​n​t​ ​t​o​ ​y​o​u​r​ ​e​m​a​i​l​.​ ​U​s​e​ ​t​h​e​ ​l​i​n​k​ ​t​o​ ​l​o​g​i​n​.
			 */
			success: string
		}
		errors: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e​.​ ​P​l​e​a​s​e​ ​u​s​e​ ​e​m​a​i​l​ ​o​n​ ​t​h​e​ ​l​o​g​i​n​ ​p​a​g​e
			 */
			failedSignInGoogle: string
		}
	}
	twoFAPage: {
		/**
		 * T​w​o​ ​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		title: string
		/**
		 * T​w​o​ ​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		pageTitle: string
		/**
		 * E​n​t​e​r​ ​t​h​e​ ​c​o​d​e​ ​f​r​o​m​ ​y​o​u​r​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​ ​t​o​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
		 */
		description: string
		/**
		 * T​w​o​ ​f​a​c​t​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​,​ ​2​F​A​,​ ​M​u​l​t​i​ ​f​a​c​t​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​,​ ​M​F​A
		 */
		keywords: string
		form: {
			/**
			 * C​o​d​e
			 */
			code: string
			/**
			 * V​e​r​i​f​y
			 */
			submit: string
			/**
			 * T​r​y​ ​a​ ​d​i​f​f​e​r​e​n​t​ ​m​e​t​h​o​d
			 */
			tryDifferentMethod: string
		}
	}
	dashboardPage: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		title: string
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		pageTitle: string
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​y​o​u​r​ ​d​a​s​h​b​o​a​r​d​.
		 */
		description: string
		/**
		 * D​a​s​h​b​o​a​r​d​,​ ​H​o​m​e​,​ ​W​e​l​c​o​m​e
		 */
		keywords: string
		navigations: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​s
			 */
			transactions: string
			/**
			 * S​a​v​e​d​ ​C​a​r​d​s
			 */
			savedCards: string
			/**
			 * H​o​w​ ​t​o
			 */
			howTo: string
		}
		userDropdown: {
			/**
			 * M​y​ ​A​c​c​o​u​n​t
			 */
			myAccount: string
			/**
			 * M​y​ ​P​r​o​f​i​l​e
			 */
			profile: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * L​o​g​o​u​t
			 */
			logout: string
		}
	}
	myProfilePage: {
		/**
		 * M​y​ ​P​r​o​f​i​l​e
		 */
		title: string
		/**
		 * M​y​ ​P​r​o​f​i​l​e
		 */
		pageTitle: string
		/**
		 * U​p​d​a​t​e​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​n​f​o​r​m​a​t​i​o​n​.
		 */
		description: string
		/**
		 * P​r​o​f​i​l​e​,​ ​A​c​c​o​u​n​t​,​ ​S​e​t​t​i​n​g​s
		 */
		keywords: string
		form: {
			/**
			 * I​D
			 */
			id: string
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			twoFactorAuth: {
				/**
				 * T​w​o​ ​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
				 */
				title: string
				/**
				 * E​n​a​b​l​e​ ​o​r​ ​d​i​s​a​b​l​e​ ​t​w​o​ ​f​a​c​t​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​o​r​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
				 */
				subtitle: string
			}
			/**
			 * R​o​l​e
			 */
			role: string
			/**
			 * U​p​d​a​t​e​ ​P​r​o​f​i​l​e
			 */
			submit: string
			/**
			 * P​r​o​f​i​l​e​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
			 */
			successStatus: string
		}
		changeEmail: {
			/**
			 * C​h​a​n​g​e​ ​E​m​a​i​l​ ​A​d​d​r​e​s​s
			 */
			title: string
			/**
			 * U​p​d​a​t​e​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.​ ​A​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​ ​t​o​ ​y​o​u​r​ ​n​e​w​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
			 */
			subtitle: string
			/**
			 * C​h​a​n​g​e​ ​e​m​a​i​l
			 */
			submit: string
			/**
			 * A​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​ ​s​e​n​t​ ​t​o​ ​y​o​u​r​ ​n​e​w​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
			 */
			successStatus: string
		}
	}
	settingsPage: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		pageTitle: string
		/**
		 * U​p​d​a​t​e​ ​y​o​u​r​ ​o​v​e​r​a​l​l​ ​a​p​p​l​i​c​a​t​i​o​n​ ​s​e​t​t​i​n​g​s​.
		 */
		description: string
		/**
		 * S​e​t​t​i​n​g​s​,​ ​A​c​c​o​u​n​t​,​ ​P​r​e​f​e​r​e​n​c​e​s​,​ ​n​o​t​i​f​i​c​a​t​i​o​n
		 */
		keywords: string
		form: {
			darkMode: {
				/**
				 * U​s​e​ ​d​a​r​k​ ​T​h​e​m​e
				 */
				title: string
				/**
				 * I​ ​k​n​o​w​ ​y​o​u​ ​l​o​v​e​ ​d​a​r​k​ ​m​o​d​e​,​ ​w​e​ ​a​l​l​ ​a​r​e​ ​�​�​.​ ​S​o​,​ ​h​e​r​e​ ​y​o​u​ ​g​o​!
				 */
				subtitle: string
			}
		}
	}
	transactionsPage: {
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​s
		 */
		title: string
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​s
		 */
		pageTitle: string
		/**
		 * V​i​e​w​ ​a​l​l​ ​y​o​u​r​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​h​e​r​e​.
		 */
		description: string
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​s​,​ ​H​i​s​t​o​r​y​,​ ​L​o​g​s​,​ ​D​e​t​a​i​l​s
		 */
		keywords: string
		statuses: {
			/**
			 * P​e​n​d​i​n​g
			 */
			pending: string
			/**
			 * R​e​v​i​e​w
			 */
			review: string
			/**
			 * S​u​c​c​e​s​s
			 */
			hold: string
			/**
			 * F​a​i​l​e​d
			 */
			done: string
			/**
			 * C​a​n​c​e​l​e​d
			 */
			canceled: string
		}
		table: {
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​I​D
			 */
			id: string
			/**
			 * A​m​o​u​n​t
			 */
			amount: string
			/**
			 * S​t​a​t​u​s
			 */
			status: string
			/**
			 * C​r​e​a​t​e​d​ ​A​t
			 */
			createdAt: string
			user: {
				/**
				 * U​s​e​r
				 */
				name: string
				/**
				 * E​m​a​i​l
				 */
				email: string
			}
			/**
			 * N​o​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​u​n​d​.
			 */
			noResults: string
		}
	}
	notifications: {
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		title: string
		/**
		 * L​a​t​e​s​t​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​a​r​e​ ​s​h​o​w​n​ ​f​i​r​s​t​.
		 */
		subtitle: string
		actions: {
			/**
			 * O​n​l​y​ ​U​n​r​e​a​d
			 */
			onlyUnread: string
			/**
			 * M​a​r​k​ ​a​l​l​ ​a​s​ ​r​e​a​d
			 */
			markAllAsRead: string
			/**
			 * S​h​o​w​ ​a​l​l​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
			 */
			showAllNotifications: string
		}
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		somethingWentWrong: string
	}
}

export type TranslationFunctions = {
	/**
	 * Dollaarr
	 */
	appName: () => LocalizedString
	/**
	 * Dollaarr - Buy and Sell Dollars at the Best Rates
	 */
	title: () => LocalizedString
	/**
	 * Dollaarr offers competitive rates for buying and selling dollars online. Secure transactions and real-time dollar rates ensure the best value for your money.
	 */
	description: () => LocalizedString
	/**
	 * Buy dollars online, sell dollars online, best dollar exchange rates, competitive currency exchange, secure dollar transactions, online dollar marketplace, dollar exchange platform, real-time dollar rates, currency exchange services, hassle-free dollar trading, dollar exchange community, online dollar trading, dollar to local currency exchange, best place to buy dollars, best place to sell dollars, Dollaarr
	 */
	keywords: () => LocalizedString
	/**
	 * @shamscorner
	 */
	appTwitterAccount: () => LocalizedString
	common: {
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Sign up
		 */
		signup: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * Hide
		 */
		hide: () => LocalizedString
		/**
		 * Or
		 */
		or: () => LocalizedString
		/**
		 * Toggle theme
		 */
		toggleTheme: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Toggle notification
		 */
		toggleNotification: () => LocalizedString
		/**
		 * Toggle navigation menu
		 */
		toggleNavigationMenu: () => LocalizedString
		/**
		 * Toggle user menu
		 */
		toggleUserMenu: () => LocalizedString
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Remove
		 */
		remove: () => LocalizedString
		/**
		 * Unknown
		 */
		unknown: () => LocalizedString
		/**
		 * Sell
		 */
		sell: () => LocalizedString
		/**
		 * Buy
		 */
		buy: () => LocalizedString
		/**
		 * Something went wrong! Please contact support.
		 */
		somethingWrong: () => LocalizedString
		/**
		 * Copied!
		 */
		copied: () => LocalizedString
		/**
		 * Reset
		 */
		reset: () => LocalizedString
		/**
		 * Scroll down to load more
		 */
		scrollDownToLoadMore: () => LocalizedString
		/**
		 * View
		 */
		view: () => LocalizedString
		/**
		 * Show / Hide columns
		 */
		toggleColumns: () => LocalizedString
		/**
		 * Pick a date
		 */
		pickDate: () => LocalizedString
	}
	appLogo: {
		/**
		 * Dollaarr offers competitive rates for buying and selling dollars online. Secure transactions and real-time dollar rates ensure the best value for your money.
		 */
		hrefTitle: () => LocalizedString
		/**
		 * Dollaarr Logo
		 */
		alt: () => LocalizedString
	}
	schemaMarkup: {
		/**
		 * Corporation
		 */
		type: () => LocalizedString
		/**
		 * Memowise Inc.
		 */
		name: () => LocalizedString
		/**
		 * Memowise is a software company that builds products to help people. We are a small team of passionate developers, designers, and entrepreneurs. We are based in Dhaka, Bangladesh.
		 */
		markupDescription: () => LocalizedString
		founder: {
			'0': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Shamim Hossain
				 */
				name: () => LocalizedString
			}
			'1': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Masud Rana
				 */
				name: () => LocalizedString
			}
			'2': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Shadman Nasif
				 */
				name: () => LocalizedString
			}
		}
		/**
		 * 2023-10-02
		 */
		foundingDate: () => LocalizedString
		contactPoint: {
			'0': {
				/**
				 * ContactPoint
				 */
				type: () => LocalizedString
				/**
				 * memowiseinc@gmail.com
				 */
				email: () => LocalizedString
				telephone: () => LocalizedString
				/**
				 * customer service
				 */
				contactType: () => LocalizedString
			}
		}
	}
	errorPage: {
		/**
		 * 404
		 */
		title: () => LocalizedString
		/**
		 * Not found
		 */
		subtitle: () => LocalizedString
		/**
		 * 404
		 */
		pageTitle: () => LocalizedString
		/**
		 * Looking for help? Reach out to us at contact@shamscorner.com
		 */
		description: () => LocalizedString
		/**
		 * Support, Contact, Help, 404, Not found
		 */
		keywords: () => LocalizedString
		/**
		 * Back to home
		 */
		backToHome: () => LocalizedString
	}
	homepage: {
		/**
		 * A production ready starter template for SvelteKit.
		 */
		title: () => LocalizedString
		/**
		 * Dollaarr offers competitive rates for buying and selling dollars online. Secure transactions and real-time dollar rates ensure the best value for your money.
		 */
		subtitle: () => LocalizedString
	}
	loginPage: {
		/**
		 * Welcome back!
		 */
		title: () => LocalizedString
		/**
		 * Log in
		 */
		pageTitle: () => LocalizedString
		/**
		 * Enter your email below and we will send you a magic link to log in to your email account.
		 */
		description: () => LocalizedString
		/**
		 * Login, Sign in, Log in, Sign up, Register
		 */
		keywords: () => LocalizedString
		form: {
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Send Magic Link
			 */
			submit: () => LocalizedString
			/**
			 * Or continue with
			 */
			continueWith: () => LocalizedString
			/**
			 * Don't have an account?
			 */
			dontHaveAccount: () => LocalizedString
			/**
			 * Forgot password?
			 */
			forgotPassword: () => LocalizedString
			/**
			 * Remember me?
			 */
			rememberMe: () => LocalizedString
			/**
			 * Continue with Google
			 */
			continueWithGoogle: () => LocalizedString
			/**
			 * Login link sent to your email. Use the link to login.
			 */
			success: () => LocalizedString
		}
		errors: {
			/**
			 * Failed to sign in with Google. Please use email on the login page
			 */
			failedSignInGoogle: () => LocalizedString
		}
	}
	twoFAPage: {
		/**
		 * Two Factor Authentication
		 */
		title: () => LocalizedString
		/**
		 * Two Factor Authentication
		 */
		pageTitle: () => LocalizedString
		/**
		 * Enter the code from your authenticator app to verify your account.
		 */
		description: () => LocalizedString
		/**
		 * Two factor authentication, 2FA, Multi factor authentication, MFA
		 */
		keywords: () => LocalizedString
		form: {
			/**
			 * Code
			 */
			code: () => LocalizedString
			/**
			 * Verify
			 */
			submit: () => LocalizedString
			/**
			 * Try a different method
			 */
			tryDifferentMethod: () => LocalizedString
		}
	}
	dashboardPage: {
		/**
		 * Dashboard
		 */
		title: () => LocalizedString
		/**
		 * Dashboard
		 */
		pageTitle: () => LocalizedString
		/**
		 * Welcome to your dashboard.
		 */
		description: () => LocalizedString
		/**
		 * Dashboard, Home, Welcome
		 */
		keywords: () => LocalizedString
		navigations: {
			/**
			 * Dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * Transactions
			 */
			transactions: () => LocalizedString
			/**
			 * Saved Cards
			 */
			savedCards: () => LocalizedString
			/**
			 * How to
			 */
			howTo: () => LocalizedString
		}
		userDropdown: {
			/**
			 * My Account
			 */
			myAccount: () => LocalizedString
			/**
			 * My Profile
			 */
			profile: () => LocalizedString
			/**
			 * Settings
			 */
			settings: () => LocalizedString
			/**
			 * Logout
			 */
			logout: () => LocalizedString
		}
	}
	myProfilePage: {
		/**
		 * My Profile
		 */
		title: () => LocalizedString
		/**
		 * My Profile
		 */
		pageTitle: () => LocalizedString
		/**
		 * Update your profile information.
		 */
		description: () => LocalizedString
		/**
		 * Profile, Account, Settings
		 */
		keywords: () => LocalizedString
		form: {
			/**
			 * ID
			 */
			id: () => LocalizedString
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			twoFactorAuth: {
				/**
				 * Two Factor Authentication
				 */
				title: () => LocalizedString
				/**
				 * Enable or disable two factor authentication for your account.
				 */
				subtitle: () => LocalizedString
			}
			/**
			 * Role
			 */
			role: () => LocalizedString
			/**
			 * Update Profile
			 */
			submit: () => LocalizedString
			/**
			 * Profile updated successfully!
			 */
			successStatus: () => LocalizedString
		}
		changeEmail: {
			/**
			 * Change Email Address
			 */
			title: () => LocalizedString
			/**
			 * Update your email address. A verification email will be sent to your new email address.
			 */
			subtitle: () => LocalizedString
			/**
			 * Change email
			 */
			submit: () => LocalizedString
			/**
			 * A verification email sent to your new email address.
			 */
			successStatus: () => LocalizedString
		}
	}
	settingsPage: {
		/**
		 * Settings
		 */
		title: () => LocalizedString
		/**
		 * Settings
		 */
		pageTitle: () => LocalizedString
		/**
		 * Update your overall application settings.
		 */
		description: () => LocalizedString
		/**
		 * Settings, Account, Preferences, notification
		 */
		keywords: () => LocalizedString
		form: {
			darkMode: {
				/**
				 * Use dark Theme
				 */
				title: () => LocalizedString
				/**
				 * I know you love dark mode, we all are 🥰. So, here you go!
				 */
				subtitle: () => LocalizedString
			}
		}
	}
	transactionsPage: {
		/**
		 * Transactions
		 */
		title: () => LocalizedString
		/**
		 * Transactions
		 */
		pageTitle: () => LocalizedString
		/**
		 * View all your transactions here.
		 */
		description: () => LocalizedString
		/**
		 * Transactions, History, Logs, Details
		 */
		keywords: () => LocalizedString
		statuses: {
			/**
			 * Pending
			 */
			pending: () => LocalizedString
			/**
			 * Review
			 */
			review: () => LocalizedString
			/**
			 * Success
			 */
			hold: () => LocalizedString
			/**
			 * Failed
			 */
			done: () => LocalizedString
			/**
			 * Canceled
			 */
			canceled: () => LocalizedString
		}
		table: {
			/**
			 * Transaction ID
			 */
			id: () => LocalizedString
			/**
			 * Amount
			 */
			amount: () => LocalizedString
			/**
			 * Status
			 */
			status: () => LocalizedString
			/**
			 * Created At
			 */
			createdAt: () => LocalizedString
			user: {
				/**
				 * User
				 */
				name: () => LocalizedString
				/**
				 * Email
				 */
				email: () => LocalizedString
			}
			/**
			 * No transactions found.
			 */
			noResults: () => LocalizedString
		}
	}
	notifications: {
		/**
		 * Notifications
		 */
		title: () => LocalizedString
		/**
		 * Latest notifications are shown first.
		 */
		subtitle: () => LocalizedString
		actions: {
			/**
			 * Only Unread
			 */
			onlyUnread: () => LocalizedString
			/**
			 * Mark all as read
			 */
			markAllAsRead: () => LocalizedString
			/**
			 * Show all notifications
			 */
			showAllNotifications: () => LocalizedString
		}
	}
	errors: {
		/**
		 * Something went wrong
		 */
		somethingWentWrong: () => LocalizedString
	}
}

export type Formatters = {}
